GET http://localhost:4250/api/auth/findJWT
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MDBiYTQ2NWU5MWQzYjMwMjAyNzI1YWYiLCJ1bmFtZSI6InJhaGlsIiwiZW1haWwiOiJyYWhpbEBkZW1vLmNvbSIsImFkZHJlc3MiOiJkZW1vIiwicm9sZXMiOlt7Il9pZCI6IjYwMGJhNDY1ZTkxZDNiMzAyMDI3MjViMCIsIm5hbWUiOiJzeXN0ZW0tYWRtaW4iLCJyZWZLZXkiOiIxMjMtMTUyMyJ9XSwic3RhdHVzIjoicGVuZGluZyIsImNyZWF0ZURhdGUiOiIyMDIxLTAxLTIzVDA0OjIxOjU3LjE1M1oiLCJfX3YiOjB9.cgR9Nu7KZ4NJVS15n_sqVgeGil3t1GAh0TSUcNq56vU

GET http://localhost:4250/api/auth/pendingUsers
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MDBiYTQ2NWU5MWQzYjMwMjAyNzI1YWYiLCJ1bmFtZSI6InJhaGlsIiwiZW1haWwiOiJyYWhpbEBkZW1vLmNvbSIsImFkZHJlc3MiOiJkZW1vIiwicm9sZXMiOlt7Il9pZCI6IjYwMGJhNDY1ZTkxZDNiMzAyMDI3MjViMCIsIm5hbWUiOiJzeXN0ZW0tYWRtaW4iLCJyZWZLZXkiOiIxMjMtMTUyMyJ9XSwic3RhdHVzIjoicGVuZGluZyIsImNyZWF0ZURhdGUiOiIyMDIxLTAxLTIzVDA0OjIxOjU3LjE1M1oiLCJfX3YiOjB9.cgR9Nu7KZ4NJVS15n_sqVgeGil3t1GAh0TSUcNq56vU

PATCH  http://localhost:4250/api/auth/setUserVerified/600ba465e91d3b30202725af
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MDBiYTQ2NWU5MWQzYjMwMjAyNzI1YWYiLCJ1bmFtZSI6InJhaGlsIiwiZW1haWwiOiJyYWhpbEBkZW1vLmNvbSIsImFkZHJlc3MiOiJkZW1vIiwicm9sZXMiOlt7Il9pZCI6IjYwMGJhNDY1ZTkxZDNiMzAyMDI3MjViMCIsIm5hbWUiOiJzeXN0ZW0tYWRtaW4iLCJyZWZLZXkiOiIxMjMtMTUyMyJ9XSwic3RhdHVzIjoicGVuZGluZyIsImNyZWF0ZURhdGUiOiIyMDIxLTAxLTIzVDA0OjIxOjU3LjE1M1oiLCJfX3YiOjB9.cgR9Nu7KZ4NJVS15n_sqVgeGil3t1GAh0TSUcNq56vU

system-admin
POST  http://localhost:4250/api/auth/login
Content-Type: application/json

{
    "email":"rahil@demo.com",
    "pwd":"123456789"
}

PUT  http://localhost:4250/api/auth/update/demo4@demo.com
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MDBiYTQ2NWU5MWQzYjMwMjAyNzI1YWYiLCJ1bmFtZSI6InJhaGlsIiwiZW1haWwiOiJyYWhpbEBkZW1vLmNvbSIsImFkZHJlc3MiOiJkZW1vIiwicm9sZXMiOlt7Il9pZCI6IjYwMGJhNDY1ZTkxZDNiMzAyMDI3MjViMCIsIm5hbWUiOiJzeXN0ZW0tYWRtaW4iLCJyZWZLZXkiOiIxMjMtMTUyMyJ9XSwic3RhdHVzIjoicGVuZGluZyIsImNyZWF0ZURhdGUiOiIyMDIxLTAxLTIzVDA0OjIxOjU3LjE1M1oiLCJfX3YiOjB9.cgR9Nu7KZ4NJVS15n_sqVgeGil3t1GAh0TSUcNq56vU
Content-Type: application/json

{
    "address":"demo4",
    "email":"demo4@demo.com",
    "pwd":"123456789"
}

POST  http://localhost:4250/api/auth/setUserUnVerifiable/60098471982adc07bcaaf503
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MDBiYTQ2NWU5MWQzYjMwMjAyNzI1YWYiLCJ1bmFtZSI6InJhaGlsIiwiZW1haWwiOiJyYWhpbEBkZW1vLmNvbSIsImFkZHJlc3MiOiJkZW1vIiwicm9sZXMiOlt7Il9pZCI6IjYwMGJhNDY1ZTkxZDNiMzAyMDI3MjViMCIsIm5hbWUiOiJzeXN0ZW0tYWRtaW4iLCJyZWZLZXkiOiIxMjMtMTUyMyJ9XSwic3RhdHVzIjoicGVuZGluZyIsImNyZWF0ZURhdGUiOiIyMDIxLTAxLTIzVDA0OjIxOjU3LjE1M1oiLCJfX3YiOjB9.cgR9Nu7KZ4NJVS15n_sqVgeGil3t1GAh0TSUcNq56vU
Content-Type: application/json

{
    "statusIssueMessage":"testing status message"
}

GET http://localhost:4250/api/auth/user/60071439bc7ea4335c48afdf
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MDBiYTQ2NWU5MWQzYjMwMjAyNzI1YWYiLCJ1bmFtZSI6InJhaGlsIiwiZW1haWwiOiJyYWhpbEBkZW1vLmNvbSIsImFkZHJlc3MiOiJkZW1vIiwicm9sZXMiOlt7Il9pZCI6IjYwMGJhNDY1ZTkxZDNiMzAyMDI3MjViMCIsIm5hbWUiOiJzeXN0ZW0tYWRtaW4iLCJyZWZLZXkiOiIxMjMtMTUyMyJ9XSwic3RhdHVzIjoicGVuZGluZyIsImNyZWF0ZURhdGUiOiIyMDIxLTAxLTIzVDA0OjIxOjU3LjE1M1oiLCJfX3YiOjB9.cgR9Nu7KZ4NJVS15n_sqVgeGil3t1GAh0TSUcNq56vU
